services:
  rustgoc:
    image: gcr.io/distroless/cc-debian12@sha256:9dac0a79194e45a7da0158a9c6da57b217585af0786db3845d1f0ec1a0dd182f
    network_mode: host
    restart: unless-stopped
    read_only: true
    user: "65532:65532"
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    working_dir: /
    command: [/app/rustgoc, -c, /config/client.toml]
    volumes:
      - ./rustgoc:/app/rustgoc:ro
      - ./client.toml:/config/client.toml:ro
      - ./secrets:/run/secrets:ro
