[package]
name = "rustgo-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
atomicwrites = "0.4.4"
base64.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
hkdf.workspace = true
rand.workspace = true
rustgo-protocol = { path = "../rustgo-protocol" }
rustgo-rendezvous = { path = "../rustgo-rendezvous" }
sha2.workspace = true
tempfile = "3.27.0"
thiserror.workspace = true
zeroize.workspace = true
x25519-dalek.workspace = true

[dev-dependencies]
proptest.workspace = true
