[package]
name = "rustgos"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
clap.workspace = true
rand.workspace = true
rustgo-config = { path = "../rustgo-config" }
rustgo-crypto = { path = "../rustgo-crypto" }
rustgo-protocol = { path = "../rustgo-protocol" }
rustgo-transport = { path = "../rustgo-transport" }
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util = { version = "0.7.19", features = ["rt"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
rcgen = "0.14.9"
rustgo-e2e = { path = "../../tests/e2e" }
tempfile = "3.27.0"
tokio = { workspace = true, features = ["test-util"] }
