[package]
name = "rustgo-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
quinn.workspace = true
rand.workspace = true
rcgen.workspace = true
rustgo-crypto = { path = "../rustgo-crypto" }
rustgo-path = { path = "../rustgo-path" }
rustgo-protocol = { path = "../rustgo-protocol" }
rustgo-rendezvous = { path = "../rustgo-rendezvous" }
rustgo-nat = { path = "../rustgo-nat" }
postcard.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tracing-subscriber.workspace = true
x509-parser = "0.18.1"

[dev-dependencies]
tempfile = "3.27.0"
